PROJECT         := tactis
DEVICES         := LPC1114
GCC4MBED_DIR    := /opt/mbed
NO_FLOAT_SCANF  := 1
NO_FLOAT_PRINTF := 1
GPFLAGS := -Os -flto
GCFLAGS := $(GPFLAGS)
USER_LIBS := ../tactis
INCDIRS := ../

include $(GCC4MBED_DIR)/build/gcc4mbed.mk
